import glob
import os

import numpy as np
import pandas as pd
import rasterio
from rasterio.enums import Resampling
from rasterio.warp import reproject

from project_layout import (
    DATA_AUDIT,
    DERIVED_RASTER_DIR,
    MASTER_DATA,
    TIMESERIES_RASTER_DIR,
    ensure_output_dirs,
)


BAND_NAMES = ["GPP", "LST", "NIRv", "Tmax", "SM", "VPD"]
REQUIRED_COVARIATES = ["NDSI", "LST", "NIRv", "Tmax", "SM", "VPD"]
GPP_SCALE_TO_DAILY_G_C_M2_DAY = 1000.0 / 8.0
GPP_ALL_ZERO_YEAR_FRACTION = 0.99


def align_raster(src_file, ref_profile, is_mask=False):
    resampling_method = Resampling.nearest if is_mask else Resampling.bilinear
    dest_array = np.full(
        (ref_profile["height"], ref_profile["width"]), np.nan, dtype=np.float32
    )
    with rasterio.open(src_file) as src:
        reproject(
            source=rasterio.band(src, 1),
            destination=dest_array,
            src_transform=src.transform,
            src_crs=src.crs,
            src_nodata=src.nodata,
            dst_transform=ref_profile["transform"],
            dst_crs=ref_profile["crs"],
            dst_nodata=np.nan,
            resampling=resampling_method,
        )
    dest_array[~np.isfinite(dest_array)] = np.nan
    return dest_array


def read_year_file(path):
    with rasterio.open(path) as src:
        data = src.read().astype("float32")
        data[~np.isfinite(data)] = np.nan
        descriptions = [desc or "" for desc in src.descriptions]
    return data, descriptions


def qc_and_convert_gpp(year_df, year):
    """Screen invalid GPP bands and convert MOD17A2H 8-day kg C units to daily g C."""
    raw = pd.to_numeric(year_df["GPP"], errors="coerce")
    finite = raw[np.isfinite(raw)]
    record = {
        "year": year,
        "finite_gpp_pixels_raw": int(len(finite)),
        "zero_gpp_pixels_raw": 0,
        "zero_fraction_raw": np.nan,
        "raw_min": np.nan,
        "raw_mean": np.nan,
        "raw_max": np.nan,
        "qc_status": "missing_in_local_tif",
    }
    year_df["GPP_Source"] = "missing_in_local_tif"
    year_df["GPP_QC_Flag"] = "no_gpp_band"
    valid_raw = raw.notna()

    if len(finite) == 0:
        return year_df, record

    zero_count = int(np.isclose(finite.to_numpy(), 0.0, atol=1e-12).sum())
    zero_fraction = zero_count / len(finite)
    raw_min = float(finite.min())
    raw_mean = float(finite.mean())
    raw_max = float(finite.max())
    record.update(
        {
            "zero_gpp_pixels_raw": zero_count,
            "zero_fraction_raw": float(zero_fraction),
            "raw_min": raw_min,
            "raw_mean": raw_mean,
            "raw_max": raw_max,
        }
    )

    if raw_max <= 0 or zero_fraction >= GPP_ALL_ZERO_YEAR_FRACTION:
        year_df["GPP"] = np.nan
        year_df["GPP_Source"] = "missing_gpp_pixel"
        year_df["GPP_QC_Flag"] = "missing_gpp_pixel"
        year_df.loc[valid_raw, "GPP_Source"] = "excluded_all_zero_gpp_band"
        year_df.loc[valid_raw, "GPP_QC_Flag"] = "excluded_all_zero_year"
        record["qc_status"] = "excluded_all_zero_gpp_band"
        return year_df, record

    year_df["GPP"] = raw * GPP_SCALE_TO_DAILY_G_C_M2_DAY
    year_df["GPP_Source"] = "missing_gpp_pixel"
    year_df["GPP_QC_Flag"] = "missing_gpp_pixel"
    year_df.loc[valid_raw, "GPP_Source"] = "MOD17A2H_qc_pass_daily_gC_m2_day"
    year_df.loc[valid_raw, "GPP_QC_Flag"] = "converted_from_8day_kg_to_daily_g"
    record["qc_status"] = "converted_from_8day_kg_to_daily_g"
    return year_df, record


def write_audit(audit_path, final_df, year_band_records, gpp_qc_records):
    year_counts = final_df.groupby("Year").size()
    gpp_sources = final_df.groupby(["Year", "GPP_Source"]).size().unstack(fill_value=0)
    gpp_qc = pd.DataFrame(gpp_qc_records)
    gpp_coverage = (
        final_df.groupby("Year")["GPP"]
        .agg(["count", "min", "mean", "max"])
        .rename(
            columns={
                "count": "qc_pass_gpp_pixels",
                "min": "gpp_min_gC_m2_day",
                "mean": "gpp_mean_gC_m2_day",
                "max": "gpp_max_gC_m2_day",
            }
        )
    )
    lines = [
        "# Master Dataset Build Audit",
        "",
        "Generated by `02_Scripts/04_data_preprocessing.py`.",
        "",
        f"- Output rows: {len(final_df):,}",
        f"- Years: {int(final_df['Year'].min())}-{int(final_df['Year'].max())}",
        "- Latest-only cleanup: no superseded master-table backup is retained.",
        "",
        "## Row Counts by Year",
        "",
        year_counts.to_string(),
        "",
        "## GPP Source by Year",
        "",
        gpp_sources.to_string(),
        "",
        "## GPP QC by Year",
        "",
        gpp_qc.to_string(index=False),
        "",
        "## QC-Passed GPP Coverage After Unit Conversion",
        "",
        gpp_coverage.to_string(),
        "",
        "## Bands Available in Local Yearly TIFFs",
        "",
    ]
    for record in year_band_records:
        lines.append(f"- {record['year']}: {', '.join(record['bands'])}")
    lines.append("")
    lines.append("## Interpretation Note")
    lines.append("")
    lines.append(
        "The local 2000-2020 yearly TIFF files contain LST, NIRv, Tmax, SM, and VPD, "
        "but do not contain GPP. The 2022 local GPP band is all zero and is excluded "
        "from response modeling as an invalid product layer. QC-passed MOD17A2H GPP "
        "values are retained for years with nonzero local GPP support and converted "
        "from scaled 8-day kg C m-2 composites to daily g C m-2 day-1 by multiplying "
        f"by {GPP_SCALE_TO_DAILY_G_C_M2_DAY:.1f}. Long-term risk projection should "
        "therefore use covariates such as VPD and NDSI, while GPP-response modeling "
        "should filter to QC-passed observed GPP rows."
    )
    with open(audit_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    print("========== Phase 3: Build expanded 2000-2023 master dataset ==========")

    ensure_output_dirs()
    ts_dir = str(TIMESERIES_RASTER_DIR)
    out_csv = str(MASTER_DATA)
    audit_path = str(DATA_AUDIT)

    mask_file = str(DERIVED_RASTER_DIR / "Hetao_CropMask_WorldCover.tif")
    ndsi_file = str(DERIVED_RASTER_DIR / "Hetao_NDSI_Spring_2023.tif")
    ts_files = sorted(glob.glob(os.path.join(ts_dir, "Hetao_EcoMeteo_Summer_*.tif")))
    if not ts_files:
        raise FileNotFoundError(f"No yearly TIFF files found in {ts_dir}.")

    with rasterio.open(ts_files[0]) as ref_src:
        ref_profile = {
            "transform": ref_src.transform,
            "crs": ref_src.crs,
            "height": ref_src.height,
            "width": ref_src.width,
        }
        cols, rows = np.meshgrid(
            np.arange(ref_src.width) + 0.5,
            np.arange(ref_src.height) + 0.5,
        )
        lons, lats = ref_src.transform * (cols, rows)

    print("Aligning crop mask and NDSI to yearly TIFF grid...")
    crop_mask = align_raster(mask_file, ref_profile, is_mask=True)
    valid_mask = crop_mask == 1
    ndsi_data = align_raster(ndsi_file, ref_profile, is_mask=False)

    valid_lons = lons[valid_mask]
    valid_lats = lats[valid_mask]
    valid_ndsi = ndsi_data[valid_mask]
    print(f"Cropland pixels retained before covariate filtering: {len(valid_lons):,}")

    all_records = []
    year_band_records = []
    gpp_qc_records = []
    for file in ts_files:
        year = int(os.path.basename(file).split("_")[-1].split(".")[0])
        data, descriptions = read_year_file(file)
        year_band_records.append({"year": year, "bands": descriptions})
        print(f"Extracting {year}: {', '.join(descriptions)}")

        year_df = pd.DataFrame(
            {
                "Year": year,
                "Lon": valid_lons,
                "Lat": valid_lats,
                "NDSI": valid_ndsi,
            }
        )
        for band in BAND_NAMES:
            if band in descriptions:
                idx = descriptions.index(band)
                year_df[band] = data[idx][valid_mask]
            else:
                year_df[band] = np.nan
        year_df, gpp_record = qc_and_convert_gpp(year_df, year)
        gpp_qc_records.append(gpp_record)
        all_records.append(year_df)

    final_df = pd.concat(all_records, ignore_index=True)
    initial_len = len(final_df)
    final_df = final_df.replace([np.inf, -np.inf], np.nan)
    final_df = final_df.dropna(subset=REQUIRED_COVARIATES + ["Lon", "Lat", "Year"])
    final_df = final_df.sort_values(["Year", "Lat", "Lon"]).reset_index(drop=True)
    print(f"Removed {initial_len - len(final_df):,} rows missing required covariates.")
    print(f"Final expanded table rows: {len(final_df):,}")
    print(final_df.groupby("Year").size().to_string())

    final_df.to_csv(out_csv, index=False)
    write_audit(audit_path, final_df, year_band_records, gpp_qc_records)
    print(f"Saved expanded master table: {out_csv}")
    print(f"Saved audit: {audit_path}")


if __name__ == "__main__":
    main()
