import glob
import os
import shutil

import numpy as np
import pandas as pd
import rasterio
from rasterio.enums import Resampling
from rasterio.warp import reproject


BAND_NAMES = ["GPP", "LST", "NIRv", "Tmax", "SM", "VPD"]
REQUIRED_COVARIATES = ["NDSI", "LST", "NIRv", "Tmax", "SM", "VPD"]


def align_raster(src_file, ref_profile, is_mask=False):
    resampling_method = Resampling.nearest if is_mask else Resampling.bilinear
    dest_array = np.full(
        (ref_profile["height"], ref_profile["width"]), np.nan, dtype=np.float32
    )
    with rasterio.open(src_file) as src:
        reproject(
            source=rasterio.band(src, 1),
            destination=dest_array,
            src_transform=src.transform,
            src_crs=src.crs,
            src_nodata=src.nodata,
            dst_transform=ref_profile["transform"],
            dst_crs=ref_profile["crs"],
            dst_nodata=np.nan,
            resampling=resampling_method,
        )
    dest_array[~np.isfinite(dest_array)] = np.nan
    return dest_array


def read_year_file(path):
    with rasterio.open(path) as src:
        data = src.read().astype("float32")
        data[~np.isfinite(data)] = np.nan
        descriptions = [desc or "" for desc in src.descriptions]
    return data, descriptions


def write_audit(audit_path, final_df, year_band_records, backup_path):
    year_counts = final_df.groupby("Year").size()
    gpp_sources = final_df.groupby(["Year", "GPP_Source"]).size().unstack(fill_value=0)
    lines = [
        "# Master Dataset Build Audit",
        "",
        "Generated by `code/04_data_preprocessing.py`.",
        "",
        f"- Output rows: {len(final_df):,}",
        f"- Years: {int(final_df['Year'].min())}-{int(final_df['Year'].max())}",
        f"- Backup of previous master table: `{os.path.basename(backup_path)}`",
        "",
        "## Row Counts by Year",
        "",
        year_counts.to_string(),
        "",
        "## GPP Source by Year",
        "",
        gpp_sources.to_string(),
        "",
        "## Bands Available in Local Yearly TIFFs",
        "",
    ]
    for record in year_band_records:
        lines.append(f"- {record['year']}: {', '.join(record['bands'])}")
    lines.append("")
    lines.append("## Interpretation Note")
    lines.append("")
    lines.append(
        "The local 2000-2020 yearly TIFF files contain LST, NIRv, Tmax, SM, and VPD, "
        "but do not contain GPP. GPP is retained as true MOD17A2H-derived values only "
        "where the local TIFF includes the GPP band, currently 2021-2023. Long-term "
        "risk projection should therefore use covariates such as VPD and NDSI, while "
        "GPP-response modeling should filter to rows with observed GPP."
    )
    with open(audit_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    print("========== Phase 3: Build expanded 2000-2023 master dataset ==========")

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(base_dir, "data")
    ts_dir = os.path.join(data_dir, "timeseries")
    out_csv = os.path.join(data_dir, "Hetao_Master_Dataset_2000_2023.csv")
    backup_csv = os.path.join(data_dir, "Hetao_Master_Dataset_2021_2023_MOD17_backup.csv")
    audit_path = os.path.join(data_dir, "Hetao_Master_Dataset_2000_2023_Audit.md")

    mask_file = os.path.join(data_dir, "Hetao_CropMask_WorldCover.tif")
    ndsi_file = os.path.join(data_dir, "Hetao_NDSI_Spring_2023.tif")
    ts_files = sorted(glob.glob(os.path.join(ts_dir, "Hetao_EcoMeteo_Summer_*.tif")))
    if not ts_files:
        raise FileNotFoundError("No yearly TIFF files found in data/timeseries.")

    if os.path.exists(out_csv) and not os.path.exists(backup_csv):
        shutil.copy2(out_csv, backup_csv)
        print(f"Backed up previous master table to: {backup_csv}")

    with rasterio.open(ts_files[0]) as ref_src:
        ref_profile = {
            "transform": ref_src.transform,
            "crs": ref_src.crs,
            "height": ref_src.height,
            "width": ref_src.width,
        }
        cols, rows = np.meshgrid(
            np.arange(ref_src.width) + 0.5,
            np.arange(ref_src.height) + 0.5,
        )
        lons, lats = ref_src.transform * (cols, rows)

    print("Aligning crop mask and NDSI to yearly TIFF grid...")
    crop_mask = align_raster(mask_file, ref_profile, is_mask=True)
    valid_mask = crop_mask == 1
    ndsi_data = align_raster(ndsi_file, ref_profile, is_mask=False)

    valid_lons = lons[valid_mask]
    valid_lats = lats[valid_mask]
    valid_ndsi = ndsi_data[valid_mask]
    print(f"Cropland pixels retained before covariate filtering: {len(valid_lons):,}")

    all_records = []
    year_band_records = []
    for file in ts_files:
        year = int(os.path.basename(file).split("_")[-1].split(".")[0])
        data, descriptions = read_year_file(file)
        year_band_records.append({"year": year, "bands": descriptions})
        print(f"Extracting {year}: {', '.join(descriptions)}")

        year_df = pd.DataFrame(
            {
                "Year": year,
                "Lon": valid_lons,
                "Lat": valid_lats,
                "NDSI": valid_ndsi,
            }
        )
        for band in BAND_NAMES:
            if band in descriptions:
                idx = descriptions.index(band)
                year_df[band] = data[idx][valid_mask]
            else:
                year_df[band] = np.nan
        year_df["GPP_Source"] = np.where(
            year_df["GPP"].notna(), "MOD17A2H_observed", "missing_in_local_tif"
        )
        all_records.append(year_df)

    final_df = pd.concat(all_records, ignore_index=True)
    initial_len = len(final_df)
    final_df = final_df.replace([np.inf, -np.inf], np.nan)
    final_df = final_df.dropna(subset=REQUIRED_COVARIATES + ["Lon", "Lat", "Year"])
    final_df = final_df.sort_values(["Year", "Lat", "Lon"]).reset_index(drop=True)
    print(f"Removed {initial_len - len(final_df):,} rows missing required covariates.")
    print(f"Final expanded table rows: {len(final_df):,}")
    print(final_df.groupby("Year").size().to_string())

    final_df.to_csv(out_csv, index=False)
    write_audit(audit_path, final_df, year_band_records, backup_csv)
    print(f"Saved expanded master table: {out_csv}")
    print(f"Saved audit: {audit_path}")


if __name__ == "__main__":
    main()
